### ISSUE TITLE
Mailing list functionaliteit

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#217]
# DO
## Phase 1
- [x] add `./nieuwsbrieven` with some pdf's from earlier nieuwsbrieven
- [x] serve them from the site

![Screenshot 2021-01-19 at 11 15 20](https://user-images.githubusercontent.com/1648248/105026977-782c0880-5a4f-11eb-95b8-03a3bdb61678.png)

Zie ook https://www.schooldehofakker.nl/nieuwsbrieven

## Phase 2
- [x] Add `MailingList` object and scaffolding
- [ ] add `subscribe` option
- [x] add `unsubscribe` option
- [ ] add change option to update email
- [x] add hofakkers parents
- [x] add mailinglist user

# DON't
- [ ] setup mailchimp for list management
- [ ] add subscription button and connect to mailchimp

**Comment by blijblijblij** [comment]
Tussenstand, voorkant is gemaakt, moet nu nog via een `ActionMailer` als echte mail verzonden worden:

<img width="1440" alt="Screenshot 2021-01-22 at 13 08 38" src="https://user-images.githubusercontent.com/1648248/105489137-1370e800-5cb3-11eb-9fa3-417cad628c58.png">

**Comment by blijblijblij** [comment]
Als mailing is verstuurd kan je deze niet nog een keer versturen:

<img width="1138" alt="Screenshot 2021-01-22 at 13 13 03" src="https://user-images.githubusercontent.com/1648248/105489506-9d20b580-5cb3-11eb-9a43-1b144032d863.png">

**Comment by blijblijblij** [comment]
Heroku does not like large attachments, as well as longer running processes, both get `KIA`,

Went around it entirely for now, pdi to the rescue

<img width="1149" alt="Screenshot 2021-01-25 at 13 10 21" src="https://user-images.githubusercontent.com/1648248/105708122-41a13280-5f14-11eb-9ecb-37d9fc44cdad.png">
<img width="941" alt="Screenshot 2021-01-25 at 13 55 59" src="https://user-images.githubusercontent.com/1648248/105708690-13702280-5f15-11eb-85d7-97f5ea6192ae.png">

**Comment by blijblijblij** [comment]
Hacked my way out of this one, pick something more robust for next round
